[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
This document describes the work carried out in the Software Architecture course project. The project consists in the development of a decentralized chat. The objetive of this chat is to provide a service in which the messages are not stored in a server but in each one of the nodes (users) of the system. The idea behind is similar to the Peer-to-Peer (P2P) approach for sharing content over the Internet.

****

=== Requirements Overview

[role="arc42help"]
****
.Contents
The main requirement is to provide a system for sending and recieving messages with any server storing this data. Therefore the system will be based on a decentralized architecture where the data storage take place locally in each node.
General overview of high-level requirements:
* Users can store their data related with their chats in their own storage Pods.
* Through the chat, users will be able to share photos, videos or any other type of files with their contacts
* When a user wants to chat with a friend, the friend will be notified by an alert
* Users can create new chat groups adding new people to them

.Motivation
With this project we want to achieve a private and point to point communication, i.e. without going through a server, thus avoiding information leaks and security problems.

.Form
Use cases				
UC1. Add Friends
UC2. Delete Friend
UC3. New Chat
	REQ001. The user will be able to add friend to the chat tool
	REQ002. The user will be able to start a chat with one or more Friends
	REQ003. The user will be able to créate new chat groups
UC4. Replay message
	REQ004. The user will be able to answer to a message sent to him
UC5. Multimedia files to a message
	REQ005. The user will be able to send multimedia files in an attachment

****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
The following table contains the persons who are specifically targeted by the application

|======================
|Role/Name   |Contact            |Expectations                                                            
| -----------      | ----------------- | ---------------------------------------------------------------- 
| Project sponsor  |  Tim Berners-Lee  |  Determine which is the best chat and which best meets the requirements 
| Professor  | Jose Emilio Labra Gayo  | Proof that the requirements are met 
| Community Manager at Solid | Mitzi   | Proof that the requirements are met 
|======================

