= dechat_es4b

image:https://travis-ci.org/Arquisoft/dechat_es4b.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/dechat_es4b"]
image:https://codecov.io/gh/Arquisoft/dechat_es4b/branch/master/graph/badge.svg["Codecov",link="https://codecov.io/gh/Arquisoft/dechat_es4b"]
image:https://api.codacy.com/project/badge/Grade/fc7dc1da60ee4e9fb67ccff782625794["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_es4b?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_es4b&utm_campaign=Badge_Grade"]


== Introduction
The project consists in the development of a decentralized chat. The objetive of this chat is to provide a service in which the messages are not stored in a server but in each one of the nodes (users) of the system. The idea behind is similar to the Peer-to-Peer (P2P) approach for sharing content over the Internet. Documentation is stored on /src/docs folder. 

== Authors:
- Avello Díaz, Enrique
- De Benito Álvarez, Carlos
- Díaz Ceñera, Mario
- Lera Cuesta, Daniel De
- Marín Iglesias, Óscar
- Menéndez De Luarca Trabanco, Lino
- Menéndez Martínez, Carlos

== Compile and run

The skeleton project is a simple Angular application which can be run as:

----
 ng serve
----

Once executed, the application should be available at: http://localhost:4200