= dechatjs_4B

image:https://travis-ci.org/Arquisoft/dechat_es4b.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/dechat_es4b"]
image:https://coveralls.io/repos/github/Arquisoft/dechat_es4b/badge.svg["Coverage status", link="https://coveralls.io/github/Arquisoft/dechat_es4b"]
image:https://api.codacy.com/project/badge/Grade/93ebff33027e4bffa7bbf77e3463d345["Codacy code quality", link="https://www.codacy.com/app/troken11/dechat_es4b?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_es4b&utm_campaign=Badge_Grade"]



== Introduction
The project consists in the development of a decentralized chat. The objetive of this chat is to provide a service in which the messages are not stored in a server but in each one of the nodes (users) of the system. The idea behind is similar to the Peer-to-Peer (P2P) approach for sharing content over the Internet. Documentation is stored on /src/docs folder. 

== Compile and run
Install node dependencies:
----
 npm i
 npm install http-server --global
----

Launch server locally:
----
 npm run build:web
 http-server
----

If you prefer you can try the app here:

https://arquisoft.github.io/dechat_es4b/app

The application is available in the IP address shown after previous command.

Launch unit tests (Asumming nmp i command has been already executed)
----
npm test
----

Launch BDD tests (Asumming nmp i command has been already executed)
----
npm run-script cucumber
----



== Authors:
- Avello Díaz, Enrique
- De Benito Álvarez, Carlos
- Díaz Ceñera, Mario
- Lera Cuesta, Daniel De
- Marín Iglesias, Óscar
- Menéndez De Luarca Trabanco, Lino
