[[section-introduction-and-goals]]
== Introduction and Goals

This document describes the work carried out in the Software Architecture course project. The project consists in the development of a decentralized chat. The objetive of this chat is to provide a service in which the messages are not stored in a server but in each one of the nodes (users) of the system. The idea behind is similar to the Peer-to-Peer (P2P) approach for sharing content over the Internet.

=== Requirements Overview



The main requirement is to provide a system for sending and recieving messages with any server storing this data. Therefore the system will be based on a decentralized architecture where the data storage take place locally in each node.
General overview of high-level requirements:

* Users can store their data related with their chats in their own storage Pods.
* Through the chat, users will be able to share photos, videos or any other type of files with their contacts
* When a user wants to chat with a friend, the friend will be notified by an alert
* Users can create new chat groups adding new people to them


With this project we want to achieve a private and point to point communication, i.e. without going through a server, thus avoiding information leaks and security problems.


.Use cases
				
* UC1. Add Friends
* UC2. New Chat
	** REQ001. The user will be able to add friend to the chat tool
	** REQ002. The user will be able to start a chat with one or more Friends
	** REQ003. The user will be able to create new chat groups
* UC3. Replay message
	** REQ004. The user will be able to answer to a message sent to him
* UC4. Multimedia files to a message
	** REQ005. The user will be able to send multimedia files in an attachment

=== Quality Goals

|======================
|Priority   |Quality            |Motivation                                                             
| 1   |  Functionality   | Users will be able to communicate effectively with others
| 2 | Descentrality  |  Avoid security issues, among others
| 3 | Usability   | We want it to be able to be used and understood by any user
| 4 | Maintanability	| We follow a model view controller with which we can revising and extending funcionalities it's easier
|======================

=== Stakeholders



The following table contains the persons who are specifically targeted by the application

|======================
|Role/Name   |Contact            |Expectations                                                             
| Project sponsor  |  SOLID |  Determine which is the best chat and which best meets the requirements 
| Professor  | Jose Emilio Labra Gayo  | Proof that the requirements are met and follow the project evolution
| Development Team | Team4B   | Develop the application that has been entrusted to us in the framework of the subject of architecture of the software
|======================

