[[section-solution-strategy]]
== Solution Strategy


=== Introduction
In this part we will documentate a short summary and explanation of the decisions and solutions in our project like technology decisions, architectonical decisions or organizational decisions.

=== Decisions
Short explanation of the decisions of the project

* *Cucumber*: it runs automated acceptance tests written in a behavior-driven development style

* *Javascript*: Is a lenguage based on ECMASCRIPT, with it we can do
applications in the web.
We will use Javascript because in the project we will implementate
a chat, as we know, and this language is the best and easiest for client
applications.

* *MochaJs*: is a JavaScript test framework for Node.js programs, featuring browser support, asynchronous testing, test coverage reports, and use of any assertion library.

* *Node.js*: Is an open-source, cross-platform JavaScript run-time 
environment that executes JavaScript code outside of a browser.

* *Solid*: Is a web decentralization project, just what we need to do the 
project.

* *Travis*: is a hosted, distributed continuous integration service used to build and test software projects hosted at GitHub.




  
=== Solution Aproaches

Once we started to do the project of the chat, we took some direct solutions. We started to programming 
in Javascript based in the project of a Solid Chess.  We will implement some integration test with Travis to take advantage of
the continuous integration service using Mocha and his assertion library to help us to prove and improve the code. We can connect to the pod and 
we can send messages with Javascript using JQuery. 
The project is implementated in Node.js which is better for us than use Angular for all the problems Angular can have for us
while Node is not difficult because we know some JavaScript.
We added some TDD testing with cucumber too which is important to prove that our code is working.
Once we can communicate with other people, that is the main purpose of this application, we added images to the communication
and chat groups to communicate with more than one person. We added the options to add friends and remove friends.
Finally we improve all of the interface of the application to make it easier to use, for this we modificate the CSS and HTML files.

