[[section-solution-strategy]]
== Solution Strategy


=== Introduction
In this part we will documentate a short summary and explanation of the decisions and solutions in our project like technology decisions, architectonical decisions or organizational decisions.

=== Decisions
Short explanation of the decisions of the project

* *Javascript*: Is a lenguage based on ECMASCRIPT, with it we can do
applications in the web.
We will use Javascript because in the project we will implementate
a chat, as we know, and this language is the best and easiest for client
applications.

* *Node.js*: Is an open-source, cross-platform JavaScript run-time 
environment that executes JavaScript code outside of a browser.

* *Solid*: Is a web decentralization project, just what we need to do the 
project.

* *MochaJs*: is a JavaScript test framework for Node.js programs, featuring browser support, asynchronous testing, test coverage reports, and use of any assertion library.
  
=== Solution Aproaches

Once we started to do the project of the chat, we took some direct solutions. We started to programming 
in Javascript based in the project of a Solid Chess.  We will implement some integration test with Mocha to
help us to prove the code. We could connect to the pod and we can send messages with Javascript.
