[[section-concepts]]
== Cross-cutting Concepts

This section describes regulation and solution ideas that are relevant in multiple
parts of our system.

=== Domain concepts

* *Domain models*

=== User Experience concepts

* *User interface* As user interface we can understand the interface of the application, in this case the interface is a
 normal chat interface like other chats applications.


=== Safety and security concepts

* *Security and safety* The security and safety in the project is key because this application is based in Solid which is
decentralized and safe. We store the information we send in the PODs to avoid  problems in the security.

=== Architecture and design patterns

* *P2P Architecture* is a commonly used computer networking architecture in which each workstation, or node, has the same capabilities 
and responsibilities.

=== “Under-the-hood” concepts

* *Persistence* to save our information, we store it on PODs on SOLID, so we don't use information stored in databases.

* *Communication and integration* in this chat we use asynchronous methods.

=== Development concepts

* *Build and code generation* The build and code generation in our project is done in javascript with Node.js. 

* *Test and deploy* For testing we use cucumber for acceptance testing and we use BDD. For asynchronous testing we use mocha.


=== Operational concepts

